// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXEd4kJZxtGuGt0-kKyLxJyTV7cYWKigg',
    appId: '1:1052329847199:web:aec15c11264112859775aa',
    messagingSenderId: '1052329847199',
    projectId: 'todo-21250',
    authDomain: 'todo-21250.firebaseapp.com',
    storageBucket: 'todo-21250.appspot.com',
    measurementId: 'G-0VZX7ZQ145',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDeytFBZbRyC8Z50AjdCzzuhgDmO49gWY',
    appId: '1:1052329847199:android:6b8bee4f58a5ea979775aa',
    messagingSenderId: '1052329847199',
    projectId: 'todo-21250',
    storageBucket: 'todo-21250.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGBn6nYc6kS0nYhP7B-6Id_iwsMQc9bOE',
    appId: '1:1052329847199:ios:ff38c80d9724edb09775aa',
    messagingSenderId: '1052329847199',
    projectId: 'todo-21250',
    storageBucket: 'todo-21250.appspot.com',
    iosBundleId: 'com.firstapp.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGBn6nYc6kS0nYhP7B-6Id_iwsMQc9bOE',
    appId: '1:1052329847199:ios:ff38c80d9724edb09775aa',
    messagingSenderId: '1052329847199',
    projectId: 'todo-21250',
    storageBucket: 'todo-21250.appspot.com',
    iosBundleId: 'com.firstapp.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXEd4kJZxtGuGt0-kKyLxJyTV7cYWKigg',
    appId: '1:1052329847199:web:a20da42a90fb16649775aa',
    messagingSenderId: '1052329847199',
    projectId: 'todo-21250',
    authDomain: 'todo-21250.firebaseapp.com',
    storageBucket: 'todo-21250.appspot.com',
    measurementId: 'G-2EKJCDX212',
  );
}
